<a href="https://colab.research.google.com/github/vardansaini/Custom-T5/blob/main/Printing_T5Details.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers
!pip install SentencePiece

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 15.5 MB/s eta 0:00:00


In [ ]:
from transformers import EncoderDecoderConfig, EncoderDecoderModel, Seq2SeqTrainingArguments, Seq2SeqTrainer, T5ForConditionalGeneration, T5Tokenizer
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
model = T5ForConditionalGeneration.from_pretrained("t5-small")

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
model.shared.weight

Parameter containing:
tensor([[ -2.0156,   0.2236,  -7.0938,  ...,  -0.3535,   2.6406,  -2.8906],
        [ 12.6250,   8.1875, -11.6250,  ...,   7.9375,  -7.3125,   0.9453],
        [ -8.7500,   7.1875,  27.8750,  ..., -26.7500,   0.8555,  -1.5156],
        ...,
        [-25.2500, -28.5000, -17.2500,  ..., -17.7500,  -5.2500,  27.3750],
        [-25.5000, -29.3750, -18.2500,  ..., -17.7500,  -4.8125,  27.7500],
        [-26.7500, -28.3750, -17.8750,  ..., -18.5000,  -7.0000,  27.6250]],
       requires_grad=True)

In [ ]:
#model.SelfAttention()

In [ ]:
model.get_encoder

<bound method T5ForConditionalGeneration.get_encoder of T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out

In [ ]:
model.eval()

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Drop

In [ ]:
dict(model.named_parameters()).keys()

dict_keys(['shared.weight', 'encoder.block.0.layer.0.SelfAttention.q.weight', 'encoder.block.0.layer.0.SelfAttention.k.weight', 'encoder.block.0.layer.0.SelfAttention.v.weight', 'encoder.block.0.layer.0.SelfAttention.o.weight', 'encoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight', 'encoder.block.0.layer.0.layer_norm.weight', 'encoder.block.0.layer.1.DenseReluDense.wi.weight', 'encoder.block.0.layer.1.DenseReluDense.wo.weight', 'encoder.block.0.layer.1.layer_norm.weight', 'encoder.block.1.layer.0.SelfAttention.q.weight', 'encoder.block.1.layer.0.SelfAttention.k.weight', 'encoder.block.1.layer.0.SelfAttention.v.weight', 'encoder.block.1.layer.0.SelfAttention.o.weight', 'encoder.block.1.layer.0.layer_norm.weight', 'encoder.block.1.layer.1.DenseReluDense.wi.weight', 'encoder.block.1.layer.1.DenseReluDense.wo.weight', 'encoder.block.1.layer.1.layer_norm.weight', 'encoder.block.2.layer.0.SelfAttention.q.weight', 'encoder.block.2.layer.0.SelfAttention.k.weight', 'encoder.blo

In [ ]:
model.decoder.final_layer_norm.weight

Parameter containing:
tensor([ 1.6406e-01,  3.1055e-01,  1.5527e-01,  1.4941e-01, -4.0627e-04,
         1.2598e-01,  2.7148e-01,  2.6367e-01,  6.7188e-01,  1.0986e-01,
         1.3477e-01,  3.5156e-01,  1.2695e-01,  1.1328e-01,  1.8750e+00,
         1.3770e-01,  1.2207e-01,  1.9727e-01,  1.5137e-01,  1.4355e-01,
         1.4941e-01,  1.0010e-01,  1.7969e-01,  7.0312e-01,  1.1963e-01,
         1.9727e-01,  1.2598e-01,  5.8984e-01,  1.1377e-01,  2.2070e-01,
         1.2598e-01,  2.6367e-01,  1.6504e-01,  1.2988e-01,  4.2969e-01,
         2.4512e-01,  1.3086e-01,  1.2451e-01,  1.3770e-01,  1.8359e-01,
         1.3086e-01,  1.0791e-01,  3.4570e-01,  1.6113e-01,  1.7285e-01,
         1.3184e-01,  2.8125e-01,  1.6992e-01,  1.6113e-01,  1.2451e-01,
         1.6699e-01,  1.7480e-01,  2.3438e-01,  4.6484e-01,  3.0469e-01,
         1.3867e-01,  1.5430e-01,  1.6895e-01,  1.1328e-01,  2.6367e-01,
         1.0889e-01,  2.9688e-01,  2.0996e-01,  1.2598e-01,  1.2305e-01,
         1.8066e-01,  1.5723e

In [ ]:
model.encoder.block[0].layer[0].layer_norm.weight

Parameter containing:
tensor([0.0918, 0.1426, 0.0762, 0.0952, 0.1855, 0.0742, 0.1152, 0.1191, 0.1592,
        0.0669, 0.0698, 0.0903, 0.0698, 0.0718, 0.1367, 0.0723, 0.0679, 0.0815,
        0.0894, 0.0796, 0.0718, 0.0522, 0.1211, 0.1406, 0.0645, 0.0894, 0.0781,
        0.1758, 0.0723, 0.1094, 0.0708, 0.1172, 0.1050, 0.0674, 0.1387, 0.1099,
        0.0845, 0.0728, 0.0776, 0.0957, 0.0728, 0.0613, 0.0684, 0.1177, 0.1138,
        0.0659, 0.2471, 0.0942, 0.0850, 0.0742, 0.0840, 0.1050, 0.1187, 0.1138,
        0.1455, 0.0825, 0.0801, 0.0845, 0.0640, 0.1475, 0.0693, 0.1133, 0.1270,
        0.0771, 0.0645, 0.1094, 0.0903, 0.0737, 0.2275, 0.1270, 0.1133, 0.0811,
        0.0825, 0.0698, 0.0776, 0.0649, 0.0728, 0.0869, 0.1045, 0.1348, 0.1406,
        0.0962, 0.0864, 0.1138, 0.0603, 0.1060, 0.0625, 0.0913, 0.0767, 0.3809,
        0.0859, 0.1108, 0.0732, 0.0869, 0.0928, 0.0811, 0.0869, 0.0605, 0.0388,
        0.0654, 0.0771, 0.0645, 0.1167, 0.1211, 0.0640, 0.0757, 0.0625, 0.0898,
        0.0903, 0.

In [ ]:
print(model.shared.weight.detach().numpy())
model.shared.weight

[[ -2.015625     0.22363281  -7.09375    ...  -0.35351562   2.640625
   -2.890625  ]
 [ 12.625        8.1875     -11.625      ...   7.9375      -7.3125
    0.9453125 ]
 [ -8.75         7.1875      27.875      ... -26.75         0.85546875
   -1.515625  ]
 ...
 [-25.25       -28.5        -17.25       ... -17.75        -5.25
   27.375     ]
 [-25.5        -29.375      -18.25       ... -17.75        -4.8125
   27.75      ]
 [-26.75       -28.375      -17.875      ... -18.5         -7.
   27.625     ]]


Parameter containing:
tensor([[ -2.0156,   0.2236,  -7.0938,  ...,  -0.3535,   2.6406,  -2.8906],
        [ 12.6250,   8.1875, -11.6250,  ...,   7.9375,  -7.3125,   0.9453],
        [ -8.7500,   7.1875,  27.8750,  ..., -26.7500,   0.8555,  -1.5156],
        ...,
        [-25.2500, -28.5000, -17.2500,  ..., -17.7500,  -5.2500,  27.3750],
        [-25.5000, -29.3750, -18.2500,  ..., -17.7500,  -4.8125,  27.7500],
        [-26.7500, -28.3750, -17.8750,  ..., -18.5000,  -7.0000,  27.6250]],
       requires_grad=True)

In [ ]:
d = dict(model.named_parameters())
for k, v in d.items():
    print(k, v)



shared.weight Parameter containing:
tensor([[ -2.0156,   0.2236,  -7.0938,  ...,  -0.3535,   2.6406,  -2.8906],
        [ 12.6250,   8.1875, -11.6250,  ...,   7.9375,  -7.3125,   0.9453],
        [ -8.7500,   7.1875,  27.8750,  ..., -26.7500,   0.8555,  -1.5156],
        ...,
        [-25.2500, -28.5000, -17.2500,  ..., -17.7500,  -5.2500,  27.3750],
        [-25.5000, -29.3750, -18.2500,  ..., -17.7500,  -4.8125,  27.7500],
        [-26.7500, -28.3750, -17.8750,  ..., -18.5000,  -7.0000,  27.6250]],
       requires_grad=True)
encoder.block.0.layer.0.SelfAttention.q.weight Parameter containing:
tensor([[-0.0162, -0.0737,  0.0042,  ...,  0.0271, -0.0366, -0.1191],
        [-0.0371, -0.0227,  0.0491,  ..., -0.0427, -0.0486,  0.0669],
        [ 0.0540, -0.0566,  0.0054,  ..., -0.0339, -0.0173, -0.0430],
        ...,
        [-0.0908,  0.0104, -0.1104,  ..., -0.0070, -0.1001,  0.0405],
        [ 0.0017,  0.0157, -0.0427,  ..., -0.0962,  0.0300,  0.0015],
        [-0.1069,  0.0002, -0.0029,

In [ ]:
df = pd.DataFrame(d)
df.to_csv('/content/drive/MyDrive/T5_Weights.CSV')

RuntimeError: ignored

In [ ]:
model.shared.weight

Parameter containing:
tensor([[ -2.0156,   0.2236,  -7.0938,  ...,  -0.3535,   2.6406,  -2.8906],
        [ 12.6250,   8.1875, -11.6250,  ...,   7.9375,  -7.3125,   0.9453],
        [ -8.7500,   7.1875,  27.8750,  ..., -26.7500,   0.8555,  -1.5156],
        ...,
        [-25.2500, -28.5000, -17.2500,  ..., -17.7500,  -5.2500,  27.3750],
        [-25.5000, -29.3750, -18.2500,  ..., -17.7500,  -4.8125,  27.7500],
        [-26.7500, -28.3750, -17.8750,  ..., -18.5000,  -7.0000,  27.6250]],
       requires_grad=True)